---

- name: Ansible Conditionals Bool
  hosts: rocky01
  vars:
    backup: false
    snapshot: false
  tasks:
    - name: Run the task if 'backup' is true
      ansible.builtin.debug:
        msg: "Congratulations"
      when: backup | bool
    
    - name: Run the task if 'backup' is false
      ansible.builtin.debug:
        msg: "Critical. Make backup."
      when: not backup

...
