---

- name: Ansible Stat
  hosts: rocky01
  tasks:
    - name: SISOP | Verificando se o arquivo existe
      ansible.builtin.stat: path=/tmp/ansible.cfg
      register: file
    
    - debug: 
        msg: "File found"
      when: file.stat.exists

    - debug:
        msg: "File not found"
      when: file.stat.exists == false

    - debug:
        msg: "Ownership has changed"
      when: file.stat.pw_name != 'root'

...
