---

- name: Update Rocky Linux Servers - Starting Deploy
  hosts: rocky01
  tasks:
   - name: DNF | Update System
     ansible.builtin.dnf: 
       name: "*"
       state: latest
       update_cache: yes

- name: Update Debian Linux Servers - Starting Deploy
  hosts: debian01
  tasks:
   - name: Debian Like | Update System
     ansible.builtin.apt: name="*" state=latest

...
