---

- name: Testando variaveis
  hosts: rocky01
  vars:
    message: "nova mensagem"
    packages:
      - htop
      - vim
  tasks:
    - name: DEBUG | {{ message }}
      ansible.builtin.debug:
        msg: "{{ message }}"

    - name: DNF | Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest

...
