---

- name: Ansible Prompt | Creating user on Linux
  hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true # Opcional - default = true
      encrypt: "md5_crypt" # Required passlib
      confirm: yes
      salt_size: 7
    - name: shell
      prompt: What is your shell?
      private: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Usuario: {{ username }} | Password: {{ password }} | Shell: {{ shell }}' 
    - name: USER | Add user
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "User create by Ansible"
        shell: "{{ shell }}"
        home: "/home/{{ username }}"
        password: "{{ password }}"

        
...
