---

# AWS EC2 dynamic inventory
# References:
#  - https://docs.ansible.com/ansible/latest/collections/amazon/aws/docsite/aws_ec2_guide.html
#  - https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html

#
#-- Plugin settings
#
plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
aws_profile: sandbox

#
# Option provides different settings to choose how the hostname will be displayed.
#
hostnames:
  #- dns-name
  #- ip-address
  #- private-ip-address

  #- name: 'private-ip-address'
  #  separator: '_'
  #  prefix: 'tag:Name'

  - name: 'ip-address'
    separator: '_'
    prefix: 'tag:Name'

#
# creates and modifies host variables from Jinja2 expressions.
#
compose:
 ansible_host: public_ip_address
 ansible_user: "'ec2-user'"

#
# You can create dynamic groups using host variables with the keyed_groups option. 
#
keyed_groups:
  - prefix: arch
    key: architecture
    value: 'x86_64'

  - prefix: instance_type
    key: instance_type

  - key: 'security_groups|json_query("[].group_id")'
    prefix: 'security_groups'

# It is also possible to create groups using the groups option.
groups:
  PROD: "'PROD' in tags.Ambiente"
  QA: "'QA' in tags.Ambiente"

# Filters (Include and Exclude)
filters:
  tag:SO:
    - 'amzn2'

exclude_filters:
- tag:Ambiente:
  - 'QA'
