---

- name: Create EC2 Instance on AWS Cloud
  hosts: localhost
  connection: local
  collections:
    - amazon.aws
  roles:
    - aws_ec2
  vars_prompt:
    - name: aws_profile
      prompt: What is your AWS profile for authentication?
      private: false
    - name: count
      prompt: How many instances do you want to create?
      private: false

...
