---

- name: SSHD | Copy sshd_config template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart sshd

...
